# Use postgres/example user/password credentials
version: '3.1'

volumes:
    db-data:
services:
    db:
        image: postgres:11.3
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - db-data:/var/lib/postgresql/data
        deploy:
            placement:
                constraints:
                    - node.role == manager
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
