# Use postgres/example user/password credentials
version: '3.1'

volumes:
    db-data:
secrets:
    postgres-password:
        file: postgres.password
services:
    db:
        image: postgres:11.3
        restart: always
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrests/postgres-password
        volumes:
            - db-data:/var/lib/postgresql/data
        deploy:
            placement:
                constraints:
                    - node.role == manager
        secrets:
            - postgres-password
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    proxy:
        image: atteo/pluralizer-proxy:1.0
        ports:
            - 80:80
    api:
        image: atteo/pluralizer:1.0
    ui:
        image: atteo/pluralizer-ui:1.0
